// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOizrbbVUq7N4BhtfQCM281wRkD2MY5qk',
    appId: '1:302213439497:web:3b6e0228666bfaf08998d8',
    messagingSenderId: '302213439497',
    projectId: 'zenith-ee621',
    authDomain: 'zenith-ee621.firebaseapp.com',
    storageBucket: 'zenith-ee621.firebasestorage.app',
    measurementId: 'G-DTYP01HPBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNfEG6-hQBt9k4vtVuh9yau4GzaZX42g',
    appId: '1:302213439497:android:03f3c115ffb571148998d8',
    messagingSenderId: '302213439497',
    projectId: 'zenith-ee621',
    storageBucket: 'zenith-ee621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmOaWt2xLFIoaEe0nOoiy_5cABfBWwI_U',
    appId: '1:302213439497:ios:414f32e082535c9b8998d8',
    messagingSenderId: '302213439497',
    projectId: 'zenith-ee621',
    storageBucket: 'zenith-ee621.firebasestorage.app',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmOaWt2xLFIoaEe0nOoiy_5cABfBWwI_U',
    appId: '1:302213439497:ios:4076ab351ff627418998d8',
    messagingSenderId: '302213439497',
    projectId: 'zenith-ee621',
    storageBucket: 'zenith-ee621.firebasestorage.app',
    iosBundleId: 'com.example.prototype.RunnerTests',
  );
}
